### ISSUE TITLE
documentation request: requirements for battery

### ISSUE THREAD

**Issue by sknebel** [solderparty/rp2040_stamp_hw#2]
(I hope this is the correct place to ask)

After looking through the documentation, I'm left with two points around the battery circuitry that I'd like to see addressed in the documentation:

a) what charge current is used by the circuitry?

b) Are there requirements regarding additional protection circuits? I.e. there doesn't seem to be explicit protection against the battery voltage running low, unless the LDO reliably shuts off at a safe point. If cells with built-in protection circuits are recommended this should be mentioned. (It's pretty much the default with pouch cells, but some users might try e.g. 18500 cells which are available both with and without protection circuits)

**Comment by arturo182** [comment]
Hi, yes this is a good place to ask.

The PROG resistor used is 2KOhm, using the formula from the MCP73831 datasheet: `1000V/2000Ohm = 500mA`.

No, there is no built-in protection for the battery, the design was made with the assumption that pretty much all modern legit batteries have one, but I will make make a note just so others are aware.
