### ISSUE TITLE
Missing Components...

### ISSUE THREAD

**Issue by naujoks-stefan** [solderparty/rp2040_stamp_hw#4]
hello, 
first of all a huge praise!!! I'm working on the rp2040 right now and it's awesome!!! I downloaded the project for Kicad. I want to build it via JLCPCB. I have two challenges. The GigaDevice 25Q64CWIG chip is no longer available. What is an alternative? JLCPCB does not support smd solder jumper. Is smd 0603 0k resistor an alternative?

best Stefan

**Comment by arturo182** [comment]
The solder jumpers are not components to be placed, they're just a bit of copper on the PCB. As for the FLASH chip, any 3.3V FLASH with the same footprint (6x5mm WSON8) and pinout should work.

**Comment by naujoks-stefan** [comment]
the answer helped me a lot. But it's not that easy to find an equivalent part without revising the entire layout ;-)) I have an additional question: WS2812B-2020 is more of a feature, isn't it? could this component be removed without affecting it? Background: JLCPCB supports this only in the standard. Here are the edge specifications min 70mmx70mm. that would be total nonsense ;-)) hence my idea to simply remove them.

**Comment by arturo182** [comment]
Hmm, if you find a flash with same footprint and pinout you shouldn't have to touch the layout at all. As for the LED, yes, it's just a nice-to-have, you can skip it and the Stamp is still functional.

**Comment by certram** [comment]
@naujoks-stefan Have you built the rp2040 stamp successfully?
