### ISSUE TITLE
Missing Silkscreen Fiducial Marker

### ISSUE THREAD

**Issue by certram** [solderparty/rp2040_stamp_hw#5]
Hello, I am new to this PCB project. I send the Bom file to PCB Manufacturer and the CSR gave the feedback to me. He tells me that I need to provide the Silkscreen Fiducial Marker. How can I generate this file from KiCad software?

**Comment by arturo182** [comment]
I'm not sure what they mean by that, the silkscreen gerber files should be enough.

**Comment by certram** [comment]
It's the coordinate of every components. Like the picture shown as follows:

**Comment by certram** [comment]
![截屏2024-08-20 09 12 08](https://github.com/user-attachments/assets/a4c1fa57-21c6-4a85-8a74-c1c2e14693ad)

**Comment by arturo182** [comment]
I am still unsure, I didn't need that for mass production.

**Comment by certram** [comment]
I use the www.jiepei.com to order. What's your website? https://www.jlc.com or other?

**Comment by arturo182** [comment]
I use JLCPCB for prototypes and Makerfabs for production.

**Comment by certram** [comment]
Thanks for replying.
